- hosts: all
  become: yes
  vars_files:
    - defaults/main.yml
    - vars/main.yml
    - vars/mysql_vars.yml
    - tmp_vars_ops/main.yml
  tasks:
    - include: tasks/main.yml
  handlers:
    - include: handlers/main.yml
