---
- include: prepare_rhel6.yml

- include: install.yml
  tags: [telegraf, install]

- include: configuration.yml
  tags: config_telegraf

- include: systemVD.yml
  tags: [telegraf, systemvd]

- include: start.yml
  tags: [tselegraf, start]
  when: telegraf_start_service
