---
- include: prepare_rhel6.yml

- include: install.yml
  tags: [telegraf, install]

- include: configure.yml
  tags: [telegraf, configure]

- include: start.yml
  tags: [tselegraf, tart]
  when: telegraf_start_service
